on: push
name: Sonar scan job
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: actions/checkout@v1
    - run: |
        mvn clean verify -P sonar -Dsonar.login=3f7c058aa32f15c30ac609ec22f77835e047d162
      env:
        GITHUB_TOKEN: 46f3cdb6cb1c519f29183f07c1373bc2779fe352
        SONAR_TOKEN: 3f7c058aa32f15c30ac609ec22f77835e047d162
